# database 연동 설정
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    check-template-location: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.250:3317/erp_dev
    username: root
    password: nex147200
  # spring data jpa 설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    me.cpdm: DEBUG
jwt:
  header: Authorization
  token-validity-in-seconds: 86400
  secret: bj30IU9hKWfjk6IPBEldxfe4Kb2LFM0msV5gFkrVVyxOJpq5lQa819ZVd2r/osY1JyZVyUcDbD/xddwKQYr8ZTUPgF73E2+sI2PR/7AiPFhTDJTsPKn3ClnBQknRu447Zr6HRCI/Z5JPX0iE1NKWVpQe4KwIDIMlSsgwj8U8eYXVRDO4/EowQ7idc6lnQM0Bn1rT5orkga1G/nJDEfrINpN+jrtQyvuDeCY8+A==
